version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: petdavila
    container_name: petdavila-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - petdavila
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: petdavila-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3307:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - petdavila

  nginx:
    image: nginx:1.17-alpine
    container_name: petdavila-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - petdavila
    depends_on:
      - app
      - db

networks:
  petdavila:
    driver: bridge
